# Generated by Django 4.2.19 on 2025-03-13 09:15

import apps.storage.models.storage
from django.db import migrations, models
import utils.fields
import utils.string_utils


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ImageStorage',
            fields=[
                ('id', utils.fields.IdField(db_index=True, default=utils.string_utils.uuid_8, help_text='ID', max_length=8, primary_key=True, serialize=False, unique=True, verbose_name='ID')),
                ('name', models.CharField(help_text='名称', max_length=32, verbose_name='名称')),
                ('thumb', models.FileField(help_text='缩略图', upload_to=apps.storage.models.storage.upload_thumb_file, verbose_name='缩略图')),
                ('file', models.FileField(help_text='文件', upload_to=apps.storage.models.storage.upload_origin_file, verbose_name='文件')),
                ('size', models.PositiveIntegerField(help_text='文件大小', verbose_name='文件大小')),
                ('width', models.PositiveIntegerField(help_text='图片宽度', verbose_name='图片宽度')),
                ('height', models.PositiveIntegerField(help_text='图片高度', verbose_name='图片高度')),
            ],
            options={
                'verbose_name': '文件存储',
                'verbose_name_plural': '文件存储',
                'db_table': 'e2_storage',
            },
        ),
    ]
